version: "3.9"

services:
  spk_cli:
    image: mkenjis/ubspkcluster1_s3_img
    volumes:
      - type: bind
        source: /root/.ssh
        target: /root/.ssh
    environment:
      - HADOOP_HOSTNAME=hdpmst
    networks:
      - mynet
    depends_on:
      - hdpmst
  hdpmst:
    image: mkenjis/ubhdpclu_img
    volumes:
      - type: bind
        source: /root/.ssh
        target: /root/.ssh
    environment:
      - HADOOP_HOST_SLAVES=hdp1,hdp2,hdp3
    networks:
      - mynet
    depends_on:
      - hdp1,hdp2,hdp3
  hdp1:
    image: mkenjis/ubhdpclu_img
    volumes:
      - type: bind
        source: /root/.ssh
        target: /root/.ssh
    networks:
      - mynet
  hdp2:
    image: mkenjis/ubhdpclu_img
    volumes:
      - type: bind
        source: /root/.ssh
        target: /root/.ssh
    networks:
      - mynet
  hdp3:
    image: mkenjis/ubhdpclu_img
    volumes:
      - type: bind
        source: /root/.ssh
        target: /root/.ssh
    networks:
      - mynet

networks:
  mynet: