version: "3.1"

services:
  spk_mst:
    image: mkenjis/ubspkcluster1_s3_img
    environment:
      - HADOOP_HOSTNAME=hdpmst    
    networks:
      - mynet
    depends_on:
      - hdpmst
  hdpmst:
    image: mkenjis/ubhdpclu_img
    environment:
      - HADOOP_HOST_SLAVES=hdp1,hdp2,hdp3
      - HADOOP_HOST_MASTER=hdpmst   
    networks:
      - mynet
    ports:
      - 9000, 8025, 8030, 8040
    depends_on:
      - hdp1,hdp2,hdp3
  hdp1:
    image: mkenjis/ubhdpclu_img
    environment:
      - HADOOP_HOST_MASTER=hdpmst
    networks:
      - mynet
  hdp2:
    image: mkenjis/ubhdpclu_img
    environment:
      - HADOOP_HOST_MASTER=hdpmst
    networks:
      - mynet
  hdp3:
    image: mkenjis/ubhdpclu_img
    environment:
      - HADOOP_HOST_MASTER=hdpmst
    networks:
      - mynet

networks:
  mynet: