version: "3.1"

services:
  kfk1:
    image: mkenjis/ubkfk_img
    environment:
      - BROKER_ID=0
    networks:
      - mynet
  kfk2:
    image: mkenjis/ubkfk_img
    environment:
      - BROKER_ID=1
    networks:
      - mynet
  kfk3:
    image: mkenjis/ubkfk_img
    environment:
      - BROKER_ID=2
    networks:
      - mynet

networks:
  mynet: